name = "greenlanDAS"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Stephanie Olinger", "Marine Denolle", "Denolle Lab"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SeisIO = "b372bb87-02dd-52bb-bcf6-c30dd83fd342"
SeisNoise = "8cc7c3c0-6b5d-11e9-39fe-c9cd0236e08b"
SineFit = "9e441e22-954e-454f-84e8-9f73a2e0fac3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10"
CUDA = "4.4"
Combinatorics = "1.0"
DSP = "0.7"
DataFrames = "1.5"
FFTW = "1.7"
Glob = "1.3"
HDF5 = "0.16"
ImageFiltering = "0.7"
Images = "0.25"
Interpolations = "0.14"
JLD2 = "0.4"
NetCDF = "0.11"
Plots = "1.38"
PyCall = "1.96"
PyPlot = "2.11"
SeisIO = "1.4"
SeisNoise = "0.5"
SineFit = "0.2"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
