[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SeisBase = "8b7dfb90-41a7-4c72-9751-87603311c074"
SeisNoise = "8cc7c3c0-6b5d-11e9-39fe-c9cd0236e08b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
